# Servlet Container & Health Setup
server:
  address: 0.0.0.0
management:
  address: 0.0.0.0
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true

# Spring Boot
spring:
  activemq:
    in-memory: false
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 10
  datasource:
    url: jdbc:mysql://localhost:3306/example?autoReconnect=true&useSSL=false
    username: root
    password: Abcd1234
#    schema: classpath:META-INF/sql/schema.sql
#    schemaUsername: ${spring.datasource.username}
#    schemaPassword: ${spring.datasource.password}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

# Camel Spring Boot
camel:
  component:
    jms:
      acknowledgement-mode-name: CLIENT_ACKNOWLEDGE
  springboot:
    name: CamelSpringBootAudit

# Logging
logging:
  config: classpath:logback.xml
  level:
    #org.apache.camel.examples: DEBUG

# Application API
api:
  base-path: /audit
  swagger:
    base-path: ${cxf.path}/${api.base-path}
    license: Apache 2.0
    license-url: http://www.apache.org/licenses/LICENSE-2.0.html
    title: Audit Service
    #terms-of-service-url: http://swagger.io/terms/
    version: 1.0.0
    description: Service for logging audit messages.
    contact: gcostanza@vandalayindustries.com
  cors:
    allowCredentials: true
    allowHeaders:
    allowOrigins:
    blockCorsIfUnauthorized: false
    defaultOptionsMethodsHandlePreflight: true
    exposeHeaders:
    findResourceMethod: true
    maxAge: 2147483647
    preflightErrorStatus: 200